#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-azure-data-lake-store-java
Version  : 2.2.9
Release  : 1
URL      : https://github.com/Azure/azure-data-lake-store-java/archive/2.2.9.tar.gz
Source0  : https://github.com/Azure/azure-data-lake-store-java/archive/2.2.9.tar.gz
Source1  : https://repo1.maven.org/maven2/com/microsoft/azure/azure-data-lake-store-sdk/2.2.9/azure-data-lake-store-sdk-2.2.9.jar
Source2  : https://repo1.maven.org/maven2/com/microsoft/azure/azure-data-lake-store-sdk/2.2.9/azure-data-lake-store-sdk-2.2.9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-azure-data-lake-store-java-data = %{version}-%{release}

%description
# Azure Datalake Store client for Java
- For an introduction to Azure Data Lake, see here: https://azure.microsoft.com/en-us/services/data-lake-store/
- For getting started introduction to the SDK, see here: https://github.com/Azure-samples/data-lake-store-java-upload-download-get-started

- For the SDK Javadoc, see here: http://azure.github.io/azure-data-lake-store-java/javadoc

%package data
Summary: data components for the mvn-azure-data-lake-store-java package.
Group: Data

%description data
data components for the mvn-azure-data-lake-store-java package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-data-lake-store-sdk/2.2.9
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-data-lake-store-sdk/2.2.9/azure-data-lake-store-sdk-2.2.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-data-lake-store-sdk/2.2.9
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-data-lake-store-sdk/2.2.9/azure-data-lake-store-sdk-2.2.9.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/microsoft/azure/azure-data-lake-store-sdk/2.2.9/azure-data-lake-store-sdk-2.2.9.jar
/usr/share/java/.m2/repository/com/microsoft/azure/azure-data-lake-store-sdk/2.2.9/azure-data-lake-store-sdk-2.2.9.pom
